### PR TITLE
WIP: udpate dependencies and configure native image

### PR DESCRIPTION
**Pull request by nkuehn**
WIP to configure GraalVM native-image to actually emit native images instead of fallback images. 

 * Uses the graalvm provided tooling to generate the configuration files.  
 * configures graal native image to fail instead of building a fallback image (we have no use for fallback images). 

Updates Kotlin to avoid an issue with the graalvm tooling and chose to update all else, too (can be reverted too). 

Status:  Does not work despite many improvments to graalvm native image in graal 21. **"Real" binaries are not possible due to Google Guice being in place. (Guice 5.0.0-beta-1 does not work either).**.   A real solution would have to remove guice for either no dependency injection or a build-time one like dagger. 

example Error message at build time is not exactly helpful to identify the piece of code that is not not supported:
```
Error: Unsupported features in 3 methods
Detailed message:
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Invoke with MethodHandle argument could not be reduced to at most a single call or single field access. The method handle must be a compile time constant, e.g., be loaded from a `static final` field. Method that contains the method handle invocation: java.lang.invoke.MethodHandle.invokeBasic()
To enable method handles that do not require LambdaForm interpretation (e.g. because of a call to MethodHandle.bindTo()) or to diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The error is then reported at run time when the invoke is executed and the method handle has to be interpreted.
```

### CODE REVIEW

**Comment by nkuehn** [comment]
Blocks https://github.com/commercetools/commercetools-docs-kit/issues/784

**Comment by nkuehn** [comment]
@jenschude  FYI I did a quick try with the new graal version here, which just confirmed that guice is the blocker for native binaries.  we're continuing with java-based builds now in the docs since removing or replacing DI with a build-time thing would be too big a refactor in rmf-codegen.

**Comment by jenschude** [comment]
I took a look into a build time DI. The main blocker is, that at the moment the generators are injected at runtime based on the configuration which language should be rendered.

**Comment by nkuehn** [comment]
Maybe a really really stupid DI question on that occasion: What's the advantage of using DI (no matter if build or run time) for such cases when the output artifact always includes and provides all generators anyways?

**Comment by jenschude** [comment]
I started refactoring to statically wire up everything and it seems feasible as I did it for one language in like 2 hours. See https://github.com/commercetools/rmf-codegen/compare/static_config?expand=1

**Comment by nkuehn** [comment]
@jenschude I rebased this on your new branch.  

The good part is that after adding some random dependencies that graalvm complained about not being able to resolve a Class a fully native image is actually building without warnings etc (and without having to allow laxer build settings that fail at runtime). 

The bad part is that the resulting binary fails with an NPE and no further information.  `🛑   java.lang.NullPointerException` (but hey, it has a red warning icon!).  Stuck again, enough for today

**Pull request closed without merging**
